export type SeedFood = {
  id: string;
  name: string;
  aliases: string[];
  category: "pakistani" | "mediterranean" | "everyday";
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  units?: Record<string, number>;
};

export const SEED_FOODS: SeedFood[] = [
  { id: "seed-chicken-breast", name: "Chicken breast", aliases: ["grilled chicken breast", "chicken breast cooked", "boiled chicken"], category: "everyday", kcal: 165, protein: 31, carbs: 0, fat: 3.6, units: { piece: 170 } },
  { id: "seed-chicken-thigh", name: "Chicken thigh", aliases: ["chicken thigh cooked", "grilled chicken thigh"], category: "everyday", kcal: 179, protein: 24.8, carbs: 0, fat: 8.2, units: { piece: 100 } },
  { id: "seed-chicken-mince", name: "Chicken mince", aliases: ["ground chicken", "chicken keema", "chicken qeema"], category: "pakistani", kcal: 189, protein: 27, carbs: 0, fat: 8.5 },
  { id: "seed-chicken-karahi", name: "Chicken karahi", aliases: ["karahi chicken", "kadai chicken"], category: "pakistani", kcal: 155, protein: 18, carbs: 4, fat: 7, units: { plate: 300, bowl: 250 } },
  { id: "seed-chicken-biryani", name: "Chicken biryani", aliases: ["biryani chicken", "chicken biriyani"], category: "pakistani", kcal: 175, protein: 10, carbs: 22, fat: 6, units: { cup: 200, plate: 350 } },
  { id: "seed-beef-biryani", name: "Beef biryani", aliases: ["biryani beef"], category: "pakistani", kcal: 195, protein: 12, carbs: 20, fat: 8, units: { cup: 200, plate: 350 } },
  { id: "seed-chicken-tikka", name: "Chicken tikka", aliases: ["tikka chicken"], category: "pakistani", kcal: 150, protein: 26, carbs: 2, fat: 4.5, units: { piece: 40 } },
  { id: "seed-tandoori-chicken", name: "Tandoori chicken", aliases: ["chicken tandoori"], category: "pakistani", kcal: 160, protein: 26, carbs: 2, fat: 5, units: { piece: 120 } },
  { id: "seed-seekh-kebab", name: "Seekh kebab", aliases: ["seekh kabab", "chicken seekh kebab"], category: "pakistani", kcal: 190, protein: 18, carbs: 3, fat: 12, units: { piece: 45 } },
  { id: "seed-shami-kebab", name: "Shami kebab", aliases: ["shami kabab"], category: "pakistani", kcal: 210, protein: 15, carbs: 8, fat: 13, units: { piece: 45 } },
  { id: "seed-chapli-kebab", name: "Chapli kebab", aliases: ["chapli kabab"], category: "pakistani", kcal: 240, protein: 16, carbs: 6, fat: 17, units: { piece: 80 } },
  { id: "seed-daal-masoor", name: "Daal masoor", aliases: ["masoor dal", "red lentil dal", "masoor daal"], category: "pakistani", kcal: 116, protein: 9, carbs: 20, fat: 0.4, units: { cup: 198, bowl: 250 } },
  { id: "seed-chana-dal", name: "Chana dal", aliases: ["chana daal", "split chickpea dal"], category: "pakistani", kcal: 130, protein: 8, carbs: 21, fat: 2.5, units: { cup: 200, bowl: 250 } },
  { id: "seed-moong-dal", name: "Moong dal", aliases: ["moong daal", "mung dal"], category: "pakistani", kcal: 105, protein: 7, carbs: 19, fat: 0.4, units: { cup: 200, bowl: 250 } },
  { id: "seed-roti", name: "Roti", aliases: ["chapati", "chapatti", "atta roti"], category: "pakistani", kcal: 297, protein: 9, carbs: 49, fat: 7, units: { roti: 40, piece: 40 } },
  { id: "seed-naan", name: "Naan", aliases: ["plain naan"], category: "pakistani", kcal: 290, protein: 9, carbs: 50, fat: 6, units: { piece: 90 } },
  { id: "seed-paratha", name: "Paratha", aliases: ["aloo paratha", "plain paratha"], category: "pakistani", kcal: 326, protein: 6.5, carbs: 42, fat: 15, units: { piece: 80 } },
  { id: "seed-haleem", name: "Chicken haleem", aliases: ["haleem", "halim"], category: "pakistani", kcal: 145, protein: 10, carbs: 12, fat: 6, units: { bowl: 300, cup: 240 } },
  { id: "seed-nihari", name: "Nihari", aliases: ["beef nihari", "nehari"], category: "pakistani", kcal: 170, protein: 14, carbs: 5, fat: 10, units: { bowl: 300 } },
  { id: "seed-keema", name: "Beef keema", aliases: ["keema", "qeema", "minced beef curry"], category: "pakistani", kcal: 190, protein: 18, carbs: 4, fat: 11, units: { cup: 200 } },
  { id: "seed-aloo-gosht", name: "Aloo gosht", aliases: ["aloo ghost", "potato beef curry"], category: "pakistani", kcal: 140, protein: 10, carbs: 8, fat: 7, units: { plate: 300, bowl: 250 } },
  { id: "seed-palak-chicken", name: "Palak chicken", aliases: ["saag chicken", "spinach chicken"], category: "pakistani", kcal: 120, protein: 14, carbs: 4, fat: 5, units: { bowl: 250 } },
  { id: "seed-aloo-palak", name: "Aloo palak", aliases: ["aloo saag", "potato spinach"], category: "pakistani", kcal: 90, protein: 3, carbs: 10, fat: 4, units: { bowl: 220 } },
  { id: "seed-chana-masala", name: "Chana masala", aliases: ["chole", "chickpea curry"], category: "pakistani", kcal: 140, protein: 7, carbs: 20, fat: 4, units: { cup: 200, bowl: 250 } },
  { id: "seed-chicken-qorma", name: "Chicken qorma", aliases: ["chicken korma", "qorma"], category: "pakistani", kcal: 175, protein: 15, carbs: 5, fat: 11, units: { bowl: 250 } },
  { id: "seed-basmati-rice", name: "Basmati rice", aliases: ["steamed basmati", "boiled basmati rice"], category: "pakistani", kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, units: { cup: 158 } },
  { id: "seed-white-rice", name: "White rice", aliases: ["steamed rice", "boiled rice", "cooked rice"], category: "everyday", kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, units: { cup: 158 } },
  { id: "seed-brown-rice", name: "Brown rice", aliases: ["cooked brown rice"], category: "everyday", kcal: 123, protein: 2.7, carbs: 26, fat: 1, units: { cup: 195 } },
  { id: "seed-raita", name: "Raita", aliases: ["cucumber raita", "yogurt raita"], category: "pakistani", kcal: 60, protein: 3, carbs: 5, fat: 3, units: { cup: 200, tbsp: 15 } },
  { id: "seed-kachumber", name: "Kachumber salad", aliases: ["kachumber", "onion tomato salad", "pakistani salad"], category: "pakistani", kcal: 35, protein: 1, carbs: 6, fat: 0.8, units: { cup: 120, bowl: 150 } },
  { id: "seed-samosa", name: "Samosa", aliases: ["chicken samosa", "aloo samosa"], category: "pakistani", kcal: 260, protein: 5, carbs: 28, fat: 14, units: { piece: 60 } },
  { id: "seed-lassi", name: "Lassi", aliases: ["sweet lassi", "mango lassi", "salted lassi"], category: "pakistani", kcal: 75, protein: 3, carbs: 10, fat: 2.5, units: { cup: 240 } },
  { id: "seed-hummus", name: "Hummus", aliases: ["houmous"], category: "mediterranean", kcal: 177, protein: 8, carbs: 14, fat: 10, units: { tbsp: 15, cup: 246 } },
  { id: "seed-falafel", name: "Falafel", aliases: ["felafel"], category: "mediterranean", kcal: 333, protein: 13, carbs: 32, fat: 18, units: { piece: 17 } },
  { id: "seed-pita", name: "Pita", aliases: ["pita bread", "whole wheat pita"], category: "mediterranean", kcal: 275, protein: 9, carbs: 56, fat: 1.2, units: { piece: 60 } },
  { id: "seed-greek-salad", name: "Greek salad", aliases: ["horiatiki"], category: "mediterranean", kcal: 90, protein: 3, carbs: 5, fat: 6, units: { bowl: 220 } },
  { id: "seed-feta", name: "Feta", aliases: ["feta cheese"], category: "mediterranean", kcal: 264, protein: 14, carbs: 4, fat: 21, units: { oz: 28 } },
  { id: "seed-olive-oil", name: "Olive oil", aliases: ["extra virgin olive oil"], category: "mediterranean", kcal: 884, protein: 0, carbs: 0, fat: 100, units: { tbsp: 14, tsp: 5 } },
  { id: "seed-olives", name: "Olives", aliases: ["kalamata olives", "black olives"], category: "mediterranean", kcal: 115, protein: 0.8, carbs: 6, fat: 11, units: { piece: 4 } },
  { id: "seed-salmon", name: "Salmon", aliases: ["grilled salmon", "baked salmon"], category: "mediterranean", kcal: 206, protein: 22, carbs: 0, fat: 12, units: { piece: 150 } },
  { id: "seed-cod", name: "White fish", aliases: ["cod", "grilled fish", "baked cod"], category: "mediterranean", kcal: 105, protein: 23, carbs: 0, fat: 0.9, units: { piece: 150 } },
  { id: "seed-tzatziki", name: "Tzatziki", aliases: ["cucumber yogurt sauce"], category: "mediterranean", kcal: 80, protein: 4, carbs: 4, fat: 5, units: { tbsp: 15 } },
  { id: "seed-tabbouleh", name: "Tabbouleh", aliases: ["tabouli"], category: "mediterranean", kcal: 80, protein: 3, carbs: 12, fat: 3, units: { cup: 160 } },
  { id: "seed-couscous", name: "Couscous", aliases: ["cooked couscous"], category: "mediterranean", kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, units: { cup: 157 } },
  { id: "seed-shawarma", name: "Chicken shawarma", aliases: ["shawarma", "chicken shawerma"], category: "mediterranean", kcal: 180, protein: 20, carbs: 4, fat: 9, units: { plate: 250 } },
  { id: "seed-lentil-soup", name: "Lentil soup", aliases: ["mediterranean lentil soup"], category: "mediterranean", kcal: 80, protein: 5, carbs: 12, fat: 1.5, units: { cup: 248, bowl: 300 } },
  { id: "seed-chickpeas", name: "Chickpeas", aliases: ["cooked chickpeas", "garbanzo beans"], category: "mediterranean", kcal: 164, protein: 8.9, carbs: 27, fat: 2.6, units: { cup: 164 } },
  { id: "seed-egg", name: "Egg", aliases: ["boiled egg", "boiled eggs", "fried egg", "scrambled egg", "eggs"], category: "everyday", kcal: 155, protein: 13, carbs: 1.1, fat: 11, units: { egg: 50, piece: 50 } },
  { id: "seed-egg-white", name: "Egg white", aliases: ["egg whites"], category: "everyday", kcal: 52, protein: 11, carbs: 0.7, fat: 0.2, units: { egg: 33, piece: 33 } },
  { id: "seed-whey", name: "Whey protein", aliases: ["whey", "protein powder", "whey isolate", "whey concentrate"], category: "everyday", kcal: 400, protein: 80, carbs: 8, fat: 4, units: { scoop: 30 } },
  { id: "seed-oatmeal", name: "Oatmeal", aliases: ["oats", "cooked oats", "porridge"], category: "everyday", kcal: 71, protein: 2.5, carbs: 12, fat: 1.5, units: { cup: 234, bowl: 250 } },
  { id: "seed-banana", name: "Banana", aliases: ["bananas"], category: "everyday", kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, units: { piece: 118 } },
  { id: "seed-apple", name: "Apple", aliases: ["apples"], category: "everyday", kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, units: { piece: 182 } },
  { id: "seed-orange", name: "Orange", aliases: ["oranges"], category: "everyday", kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, units: { piece: 131 } },
  { id: "seed-berries", name: "Mixed berries", aliases: ["berries", "blueberries", "strawberries"], category: "everyday", kcal: 43, protein: 0.7, carbs: 10, fat: 0.3, units: { cup: 150 } },
  { id: "seed-broccoli", name: "Broccoli", aliases: ["cooked broccoli", "steamed broccoli"], category: "everyday", kcal: 35, protein: 2.4, carbs: 7, fat: 0.4, units: { cup: 156 } },
  { id: "seed-sweet-potato", name: "Sweet potato", aliases: ["baked sweet potato"], category: "everyday", kcal: 90, protein: 2, carbs: 21, fat: 0.2, units: { piece: 130, cup: 200 } },
  { id: "seed-potato", name: "Potato", aliases: ["boiled potato", "baked potato"], category: "everyday", kcal: 87, protein: 1.9, carbs: 20, fat: 0.1, units: { piece: 150, cup: 156 } },
  { id: "seed-ground-turkey", name: "Ground turkey", aliases: ["turkey mince", "lean ground turkey"], category: "everyday", kcal: 170, protein: 28, carbs: 0, fat: 7 },
  { id: "seed-sirloin", name: "Sirloin steak", aliases: ["grilled sirloin", "lean beef", "beef steak"], category: "everyday", kcal: 180, protein: 29, carbs: 0, fat: 6.5, units: { piece: 170 } },
  { id: "seed-lamb", name: "Lamb", aliases: ["grilled lamb", "lamb curry meat"], category: "everyday", kcal: 243, protein: 25, carbs: 0, fat: 15, units: { piece: 150 } },
  { id: "seed-greek-yogurt", name: "Greek yogurt", aliases: ["nonfat greek yogurt", "plain greek yogurt", "yoghurt"], category: "everyday", kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, units: { cup: 170 } },
  { id: "seed-cottage-cheese", name: "Cottage cheese", aliases: ["low fat cottage cheese"], category: "everyday", kcal: 81, protein: 11, carbs: 4.3, fat: 2.3, units: { cup: 226 } },
  { id: "seed-milk", name: "Milk 2%", aliases: ["milk", "2 percent milk"], category: "everyday", kcal: 50, protein: 3.3, carbs: 4.8, fat: 2, units: { cup: 244 } },
  { id: "seed-skim-milk", name: "Skim milk", aliases: ["nonfat milk", "fat free milk"], category: "everyday", kcal: 34, protein: 3.4, carbs: 5, fat: 0.1, units: { cup: 245 } },
  { id: "seed-whole-milk", name: "Whole milk", aliases: ["full fat milk"], category: "everyday", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, units: { cup: 244 } },
  { id: "seed-wheat-bread", name: "Whole wheat bread", aliases: ["wheat bread", "whole grain bread"], category: "everyday", kcal: 247, protein: 13, carbs: 41, fat: 4.2, units: { slice: 28, piece: 28 } },
  { id: "seed-white-bread", name: "White bread", aliases: ["sandwich bread"], category: "everyday", kcal: 265, protein: 9, carbs: 49, fat: 3.2, units: { slice: 25, piece: 25 } },
  { id: "seed-almonds", name: "Almonds", aliases: ["almond"], category: "everyday", kcal: 579, protein: 21, carbs: 22, fat: 50, units: { oz: 28 } },
  { id: "seed-mixed-nuts", name: "Mixed nuts", aliases: ["nuts", "trail mix nuts"], category: "everyday", kcal: 607, protein: 20, carbs: 21, fat: 54, units: { oz: 28 } },
  { id: "seed-peanut-butter", name: "Peanut butter", aliases: ["pb"], category: "everyday", kcal: 588, protein: 25, carbs: 20, fat: 50, units: { tbsp: 16 } },
  { id: "seed-salad", name: "Green salad", aliases: ["salad", "salad greens", "lettuce salad", "side salad"], category: "everyday", kcal: 20, protein: 1.5, carbs: 3, fat: 0.3, units: { bowl: 80, cup: 36 } },
  { id: "seed-cucumber", name: "Cucumber", aliases: ["cucumbers"], category: "everyday", kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, units: { cup: 104 } },
  { id: "seed-tomato", name: "Tomato", aliases: ["tomatoes"], category: "everyday", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, units: { piece: 123, cup: 180 } },
  { id: "seed-avocado", name: "Avocado", aliases: ["avocados"], category: "everyday", kcal: 160, protein: 2, carbs: 8.5, fat: 15, units: { piece: 136 } },
  { id: "seed-protein-bar", name: "Protein bar", aliases: ["protein bars"], category: "everyday", kcal: 333, protein: 33, carbs: 35, fat: 10, units: { piece: 60 } },
  { id: "seed-tuna", name: "Tuna in water", aliases: ["canned tuna", "tuna"], category: "everyday", kcal: 116, protein: 26, carbs: 0, fat: 0.8, units: { can: 112 } },
  { id: "seed-quinoa", name: "Quinoa", aliases: ["cooked quinoa"], category: "everyday", kcal: 120, protein: 4.4, carbs: 21, fat: 1.9, units: { cup: 185 } },
  { id: "seed-pasta", name: "Pasta", aliases: ["cooked pasta", "spaghetti", "penne"], category: "everyday", kcal: 131, protein: 5, carbs: 25, fat: 1.1, units: { cup: 140 } },
  { id: "seed-cheddar", name: "Cheddar", aliases: ["cheddar cheese"], category: "everyday", kcal: 403, protein: 23, carbs: 3.1, fat: 33, units: { slice: 28, oz: 28 } },
  { id: "seed-butter", name: "Butter", aliases: [], category: "everyday", kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, units: { tbsp: 14, tsp: 5 } },
  { id: "seed-honey", name: "Honey", aliases: [], category: "everyday", kcal: 304, protein: 0.3, carbs: 82, fat: 0, units: { tbsp: 21, tsp: 7 } },
  { id: "seed-dates", name: "Dates", aliases: ["date", "medjool dates"], category: "everyday", kcal: 277, protein: 1.8, carbs: 75, fat: 0.2, units: { piece: 24 } },
  { id: "seed-mango", name: "Mango", aliases: ["mangoes"], category: "everyday", kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, units: { cup: 165, piece: 200 } },
  { id: "seed-spinach", name: "Spinach", aliases: ["cooked spinach", "palak"], category: "everyday", kcal: 23, protein: 3, carbs: 3.8, fat: 0.3, units: { cup: 180 } },
  { id: "seed-cauliflower", name: "Cauliflower", aliases: ["cooked cauliflower", "gobi"], category: "everyday", kcal: 23, protein: 1.8, carbs: 4.1, fat: 0.5, units: { cup: 124 } },
  { id: "seed-green-beans", name: "Green beans", aliases: ["cooked green beans"], category: "everyday", kcal: 35, protein: 1.9, carbs: 7.9, fat: 0.3, units: { cup: 125 } },
  { id: "seed-coffee", name: "Black coffee", aliases: ["coffee", "americano"], category: "everyday", kcal: 2, protein: 0.3, carbs: 0, fat: 0, units: { cup: 240 } },
];
